### ISSUE TITLE
Evaluation on AFLW2000 seems flawed (not comparable to others)

### ISSUE THREAD

**Issue by sifeluga** [vitoralbiero/img2pose#17]
Hi,
first of all congrats for achieving great results on head pose estimation. I find it quite impressive what's possible with such an implicit approach (going from automatized WIDER pose annotations, where surely there is some error on the ground-truth data itself). On BIWI your results seem to set new SOTA accuracy. 

Yet, for AFLW2000 it seems you are comparing your predicted pose rotation with the _ground-truth (GT) that you generated yourself_ via fitting your own n-pt model to the landmarks via:
` _, pose_target = get_pose(threed_points, target_points, image_intrinsics)`, 
which basically uses solvepnp: 
`        retval, rvecs, tvecs = cv2.solvePnP(
            threed_landmarks,
            twod_landmarks,
            camera_intrinsics,
            None,
            flags=cv2.SOLVEPNP_EPNP)`

**Now the problem is that AFLW2000 provides ground-truth headpose information in euler angles that all the other authors have used, to which you are now comparing your results based on your own pose GT in your paper (Table1):**
![image](https://user-images.githubusercontent.com/19574863/110459400-37ef1b00-80cd-11eb-887f-d839da4945ef.png)

Please correct me if I am wrong with those assumptions. Assuming I understood your evaluation correct, that means everyone compares to the data is provided with AFLW2000, while you are comparing and basing your result metrics on your data. Hence, it is not comparable unless 1) you also use the provided ground-truth or 2) rerun the experiments of the other authors while providing your data, which at the minimum would raise the question as to why your ground-truth is more correct?

PS: I reran your model (single scale) using approach 1) but only achieved an MAE accuracy above 7 degrees... 

Best regards,
Felix

**Comment by vitoralbiero** [comment]
Hello Felix,

Thank you for your interest in our work!
We are solving a much harder problem than pose estimation, since face detection faces are much harder than faces in pose benchmarks, so we had to create our own labels for training. These labels were created using our own 3D model, thus we tested on AFLW2000-3D using labels created by the ground-truth landmarks and our 3D model.

For approach 1), we compared it with the AFLW2000-3D ground-truth pose labels and got similar results (both single and multi-scale). Because our representation is similar to BIWI, in order to compare to AFLW2000-3D, you need to convert our predicted labels using the function below.

```
pose_target[:3] = Rotation.from_euler('xyz', pose_para, degrees=False).as_euler('zxy', degrees=True)
pose_pred[:3] = Rotation.from_euler('xyz', convert_to_aflw(pose_pred[:3]), degrees=True).as_euler('zxy', degrees=True)

def convert_to_aflw(rotvec):
    rot_mat_1 = Rotation.from_rotvec(rotvec).as_matrix()
    rot_mat_2 = np.transpose(rot_mat_1)
    angle = Rotation.from_matrix(rot_mat_2).as_euler('xyz', degrees=True)
    return np.array([angle[0], -angle[1], -angle[2]])
```
For approach 2), although unfeasible since the majority of other methods are not publicly available, a similar conversion would be required.

Hope this helps.
