### ISSUE TITLE
What is the result of the training script in README? Why is the batch_size = 2 in your training scripts? 

### ISSUE THREAD

**Issue by KindleHe** [vitoralbiero/img2pose#20]
@vitoralbiero 
hello，nice to try your great job, 
however, I have 2 questions:
What is the result of the training script in README? 
Why is the batch_size = 2 in your training scripts? 
  -  why not 4, 16, or 64?
  -  Doethe result differ much for different batch_size?
```shell
CUDA_VISIBLE_DEVICES=0 python3 train.py
--pose_mean ./datasets/lmdb/WIDER_train_annotations_pose_mean.npy
--pose_stddev ./datasets/lmdb/WIDER_train_annotations_pose_stddev.npy
--workspace ./workspace/
--train_source ./datasets/lmdb/WIDER_train_annotations.lmdb
--val_source ./datasets/lmdb/WIDER_val_annotations.lmdb
--prefix trial_1
--batch_size 2
--lr_plateau
--early_stop
--random_flip
--random_crop
--max_size 1400
```
Thanks for your kind-hearted reply!

**Comment by vitoralbiero** [comment]
Hello @KindleHe,

Thanks for your interest in our work.

This script was the one used to achieve the results shown in the paper.

We are using image batch size of 2 because of memory constraints. With image batch size 2, the RPN batch size is 512 (2x256) and the pose head batch size is 1024 (512x2).
In order to allow for larger image batch sizes, multiple GPU training would be required, and as of now, our training pipeline is not fully implemented for distributed parallel training, but PRs are welcome.

Hope this helps.
