### ISSUE TITLE
Questions related to the bbox and landmark values

### ISSUE THREAD

**Issue by vujadeyoon** [vitoralbiero/img2pose#22]
Dear Vítor Albiero,

After the publication of the RetinaFace paper about three years ago, I think this paper is very interesting and meaningful for detecting face and estimating head pose.
In particular, I believe that your work collecting and refining data for the start of new research (e.g 6DoF) will have a good impact on the academic and industrial world.

I have three questions while analyzing your code and reading the paper.

1. Why does you use the RetinaFace's predicted values for face bbox and landmarks, not the RetinaFace's annoated values [1] ? Do you have any special reasons? For reference, RetinaFace authors provide additional annotated landmark coordinate values. In other words, the bbox values are not changed compared to the original WIDERFACE bbox values for the GT.

2. When looking at the json files provided as annotations [2], there are 5 or 68 landmarks depending on the type of data (i.e. face in the WIDERFACE dataset). According to your paper, img2pose, the 5-point-landmarks of the RetinaFace was utilized to estimate 6DoF values in the sub-section 4.1. This confuses me. How do you get 68 landmark values? and why did the number of landmark values differ (e.g. 5 or 68)?

3. This question 3 is related to the above question 1. Since I analyzed the code, the bbox values used to get the 6DoF is not the original WIDERFACE bbox value as far as I mentioned above. Although img2pose didn't use the bbox coordinates for training (i.e. it is not used for loss.), I think the use of non-GT values for the WIDERFACE dataset affect the performance for predicting the face bbox on the WIDERFACE. What is your opinion for this? A example between the GT bbox values for original WIDERFACE and img2pose are below. The order of coordinates can be different. However, even when converting coordinate values, their values are clearly different.
    - image: 0--Parade/0_Parade_marchingband_1_849.jpg
    - original GT bbox form WIDERFACE: 449 330 122 149
    - img2pose GT bbox from code [3]: 442 310 578 473 

Best regards,
vujadeyoon

[1] https://github.com/deepinsight/insightface/tree/master/detection/RetinaFace
[2] https://github.com/vitoralbiero/img2pose/wiki/Annotations
[3] imgs, targets = data in the train.py; data_dict = targets[0]; boxes = data_dict['boxes'].numpy().tolist()

**Comment by vitoralbiero** [comment]
Hello Sungjun Ethan Yoon,

Thanks for your interest in our work!

Regarding your questions:

1. As RetinaFace provides manually annotated landmarks for only 76k training faces and none for validation faces, we use its prediction for the rest of the training faces (63k) and validation faces (34k) that do not contain landmarks. For the manually annotated landmarks, the original bbox is used to estimate the 6DoF. For the other ones, we use the bbox prediction, as in our experiments it resulted in better 6DoF estimation since the predicted landmarks are more centered.

2. For some faces, we refined the 5 landmark predictions from RetinaFace using a 68 landmark detector by matching the center of the eyes of the two landmark sets. But this step is not necessary, as similar results are achieved while only using RetinaFace's 5 landmark predictions.

3. For training, it won't matter which bbox is stored, as the bbox is actually projected from the 6DoF during training, and is customizable. And, as I said in answer 1, we used a mix of WIDER FACE GT bbox and RetinaFace bbox to estimate 6DoF labels for training.
The original and img2pose bbox you posted are in different formats: the original is left top width height; while ours are left top right bottom.

Hope this answers your questions.

**Comment by vujadeyoon** [comment]
Dear Vítor Albiero,

Thanks for helpful answers.
I clearly understand what you are saying, and all of questions are solved due to your answers.

Could I get the information about the used 68 landmark detector (paper or code)?

Best,
vujadeyoon

**Comment by vitoralbiero** [comment]
Yes, we used this [code](https://github.com/1adrianb/face-alignment).
It has good predictions when dealing with large faces, but it is very unstable with medium and small faces (which WIDER FACE is mainly composed of).
