### ISSUE TITLE
Regarding yaw, pitch and roll in test_own_images.ipynb

### ISSUE THREAD

**Issue by 97jay** [vitoralbiero/img2pose#27]
Hi, can you please help me how to get yaw, pitch and roll angles in test_own_images.ipynb.
Thank you so much

**Comment by vujadeyoon** [comment]
Dear 976jay,

You can find code [1] that you want in the jupyter cell, Run on a folder or an image list.
I think the variable, pose_pred, includes information related to the yaw, pitch, and roll angles as well as 3D translation coordinate values (i.e. x, y, z)

Best,
vujadeyoon


[1] pose_pred = res["dofs"].cpu().numpy()[i].astype('float')

**Comment by 97jay** [comment]
I will look into this. Thank you so much

**Comment by vitoralbiero** [comment]
Thanks @vujadeyoon

Yes, the pose_pred includes rotation vectors (left axis rotation, top axis rotation, front axis rotation) and translation coordinates.
If you want pitch, yaw and roll (in this order) on the same format as AFLW2000 dataset, you can use the conversion below:
```
def convert_to_aflw(rotvec, is_rotvec=True):
    if is_rotvec:
        rotvec = Rotation.from_rotvec(rotvec).as_matrix()
    rot_mat_2 = np.transpose(rotvec)
    angle = Rotation.from_matrix(rot_mat_2).as_euler('xyz', degrees=True)
    
    return np.array([angle[0], -angle[1], -angle[2]])
```
However, this format suffers from a problem where yaw is limited to (-90, 90) degrees, and if go beyond this point, pitch and roll are affected to compensate.

Otherwise, just used the first three values from the pose_pred which corresponds to the rotation vector.

Hope this helps.

**Comment by 97jay** [comment]
Ok I got your point. Thank you for letting me know.
