### ISSUE TITLE
Questions related to image and target transformation

### ISSUE THREAD

**Issue by chiaitian** [vitoralbiero/img2pose#30]
Dear Vítor Albiero,
I have one questions about the image and target transformation in the train phasse:

The model has a transformation GeneralizedRCNNTransform before the image and target passing to the network. This transformation will resize the image , bbox  and keypoints, but no pose, mentioned in #28 [2]. I wonder if should recalculate the global pose accordding the resized image, bbox, keypoints.

best regards!

**Comment by vitoralbiero** [comment]
Hello,

The GeneralizedRCNNTransform only resizes the image and the box, there are no keypoints been feed from the data loader.
When the image and bbox are resized, there is no need to recalculate the pose, as it should be the same no matter the size of the image.
When rendering, you will use a camera intrinsic that will need to match your resized image, so that the pose is correctly transformed.

You only need to recompute pose if you perform augmentations like random crop, or random flip. But the data loader also is taking care of this.

Hope this helps.
