### ISSUE TITLE
About Assumption of Focal length

### ISSUE THREAD

**Issue by KindleHe** [vitoralbiero/img2pose#31]
As the paper said in appendix A, "**Here, we assume f equals the image crop height, h_bb,
plus width, w_bb**". 

Namely, the **focal length f** for image crop perspective  is assumed as **w_bb + h_bb**.

Here, could we assume **focal lenth f** to other value ,such as **w_bb + h_bb + 1**, or something else?

**Comment by vitoralbiero** [comment]
The training labels were calculated using **f = w<sub>bb</sub> + h<sub>bb</sub>**, so we use that when converting to global pose, as the pose is relative to that bbox size.
You can convert the poses to other focal length simply by converting from local to global, and then converting back to your new bbox with **f = w<sub>bb</sub>, h<sub>bb</sub> + 1**.
Or you can modify our code to instead of converting from local to global, converting from local to another bigger/small local version.

Hope this helps.
