### ISSUE TITLE
Testing with WIDER FACE dataset

### ISSUE THREAD

**Issue by solefullife** [vitoralbiero/img2pose#33]
Thank you for the open-source code. In section WIDER FACE dataset evaluation in readme, you use validation data instead of test data. Could you also explain this? Am I missing something?
Could you give some more details on how to evaluate your network on pretrained models to get the results mentioned in the paper for WIDER FACE dataset in Testing section of readme?

Thanks a lot for your help :)

**Comment by vitoralbiero** [comment]
Hello,

Thank you for your interest.

We are using the validation in there because we cannot compute the test error ourselves, instead, the results need to be sent to the WIDER FACE authors.
If you want to run on the test set, simply follow the instructions in [WIDER FACE dataset evaluation](https://github.com/vitoralbiero/img2pose#wider-face-dataset-evaluation), replacing the validation for the test as:
```
python3 evaluation/evaluate_wider.py 
--dataset_path datasets/WIDER_Face/WIDER_test/images/
--dataset_list datasets/WIDER_Face/wider_face_split/wider_face_test_filelist.txt
--pose_mean models/WIDER_train_pose_mean_v1.npy 
--pose_stddev models/WIDER_train_pose_stddev_v1.npy
--pretrained_path models/img2pose_v1.pth
--output_path results/WIDER_FACE/Test/
```

Then, to get the mAP and curves, you will need to zip the ``results/WIDER_FACE/Test/`` folder and send to the WIDER FACE authors.

Hope this helps.
