### ISSUE TITLE
how to get the  Yaw Pitch Roll X Y Z when testing?

### ISSUE THREAD

**Issue by ghost** [vitoralbiero/img2pose#36]
![1](https://user-images.githubusercontent.com/40932226/119639509-433f2080-be4a-11eb-9163-1b387f7c71e7.PNG)

how to get the  Yaw Pitch Roll X Y Z when testing?

**Comment by ghost** [comment]
why the results of \WIDER_FACE\Val\11--Meeting\11_Meeting_Meeting_11_Meeting_Meeting_11_560.txt
is 5 number?
421.0 231.0 10.0 10.0 0.97
what is 5 number mean?
why not 6 number (Yaw Pitch Roll X Y Z )?

**Comment by vitoralbiero** [comment]
Hello,

Thank you for your interest in our project.

I believe the result you got was using ```evaluate_wider.py```, which is a script used to evaluate face detection, where the output is the bounding box [left, top, width, height] and the face score.

To get the pose prediction [r<sub>x</sub>, r<sub>y</sub>, r<sub>z</sub>, t<sub>x</sub>, t<sub>y</sub>, t<sub>z</sub>], check ```pose_pred``` at [test_own_images.ipynb](https://github.com/vitoralbiero/img2pose/blob/main/evaluation/jupyter_notebooks/test_own_images.ipynb), or ```all_poses``` at [run_face_alignment.py](https://github.com/vitoralbiero/img2pose/blob/main/run_face_alignment.py#L75).
If you want Euler Yaw, Pitch, Roll instead of the predicted rotation vector, look for the conversion ```convert_to_aflw()``` at [aflw_2000_3d_evaluation.ipynb](https://github.com/vitoralbiero/img2pose/blob/main/evaluation/jupyter_notebooks/aflw_2000_3d_evaluation.ipynb).

Hope this helps.
