### ISSUE TITLE
Some questions about 68 facial landmarks

### ISSUE THREAD

**Issue by tkzky** [vitoralbiero/img2pose#44]
hello. I have some questions:
1. How do I get the (tx, ty, tz) coordinates of 68 facial landmarks?
2. What is the physical meaning of the tz coordinate? Is it the depth of the feature point relative to the camera?
3. How do I run the code through the camera to get the  pose prediction [rx, ry, rz, tx, ty, tz]

Looking for your reply! Thank you

**Comment by vitoralbiero** [comment]
Hello @tkzky, thanks for your interest in our work!

1. You can use OpenCV SolvePnP to estimate the translation (and rotation) of 68 facial landmarks and some 3D 68 points (for instance, the one we have in this repo). This was the way that the weakly-supervised training data was created, except that we used 5 points instead of 68.
2. In our case, T<sub>z</sub> is the front/back distance between the face and the camera, similar to how T<sub>x</sub> is the left/right, and T<sub>y</sub> is top/down.
3.  Install the code following the [Installation](https://github.com/vitoralbiero/img2pose#installation) guide, then follow steps in [Testing](https://github.com/vitoralbiero/img2pose#testing) to download the pre-trained model, and use the [test_own_images](https://github.com/vitoralbiero/img2pose/blob/main/evaluation/jupyter_notebooks/test_own_images.ipynb) notebook to run on your images.

Hope this helps.
