### ISSUE TITLE
Question about this work

### ISSUE THREAD

**Issue by FunkyKoki** [vitoralbiero/img2pose#58]
Forgive me, can I infer that, **your work just replaces the `bbox regression` in the second stage of Faster-RCNN by `pose regression`**?

I didn't mean to offend, the pose transformation between global and local is enlightening.
But, is my infer true?

**Comment by vitoralbiero** [comment]
As stated in the paper, we build our method on top of Faster-RCNN, so replacing the bbox head with pose head is one of the contributions of our work.
Replacing the bbox head with pose head without the pose transformation would not work, so that is another contribution.
You can read the other contributions in our paper.

**Comment by FunkyKoki** [comment]
Your work is actually very nice, and thank you for all your contributions.
