### ISSUE TITLE
Question about Visualizing the Activation Map on each layer of the model

### ISSUE THREAD

**Issue by RookieDookie123** [vitoralbiero/img2pose#66]
Dear Vítor Albiero,

Thank you for your amazing work !
I wish to visualize an activation map on each layer of the model, can I ask which layer should I looking into and how can I visualize it?
Thank you in advance !

best regards!

**Comment by vitoralbiero** [comment]
Hello @RookieDookie123,

Thank you for your interest in our work!

You should focus on the backbone outputs, which are used in the heads to predict the class (face/non-face) and the 6DoFs.
We don't have code written to visualize the class activation maps, but since our method is built on top of Faster-RCNN, you could follow [this](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.ipynb) or other tutorial to write the code yourself.
If you do, PMs are welcomed!

I hope this helps.
