### ISSUE TITLE
A question about K_box and K_img.

### ISSUE THREAD

**Issue by FengWei2000** [vitoralbiero/img2pose#72]
Hello!@vitoralbiero ,

I am confused about the K_box in your paper, I cant't understand the physical and practical meaning of the K_box。

I can understand the physical and practical meaning of w+h, w/2 and h/2 in the K_img.

![image](https://user-images.githubusercontent.com/47074522/197783892-d46b32fb-6c8a-483c-9ae9-3f6921152abd.png)

However, I can't understand the cx+x and cy+y in the K_box. What's the meaning of them?  Why do you set K_box in this way? Is there any reference?

![image](https://user-images.githubusercontent.com/47074522/197785139-2ab51dc6-8d7c-4f28-beb9-48178bad3c6c.png)

Thank you for your help!

**Comment by vitoralbiero** [comment]
Hello @FengWei2000,

Since the pose is relative to the center of the bbox, when moving to the full image, we need to know where that pose is coming from. That's why we set set K_box focal point to ( $c_x + x$, $c_y + y$ ), which is the bbox center location w.r.t. the full image. Having this enables us to then convert the pose from this focal point to the full image focal point ( $1/2w$, $1/2h$ ), using the proposed algorithm.

Hope this helps.
